name: 自动停止加速

on:
  push:
  schedule:
   # 定时任务，北京时间24点执行任务 16 + 8 = 24
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm instal
        run: |
          npm install
      - name: "加速器暂停脚本"
        run: |
          node main.js
        env:
          LEISHEN_USERNAME: ${{ secrets.LEISHEN_USERNAME }}
          LEISHEN_PASSWORD: ${{ secrets.LEISHEN_PASSWORD }}
          NOTICE_TOKEN: ${{ secrets.NOTICE_TOKEN }}
      - name: "Notice"
        run: |
          chmod a+x notice.sh
          ./notice.sh "${{ secrets.NOTICE_TOKEN }}"
